[package]
name = "hailort-sys"
version = "0.1.1"
edition = "2024"
description = "Raw FFI bindings to the HailoRT C runtime library"
license = "MIT"
repository = "https://github.com/quinnjr/hailort-sys"

[lib]
name = "hailort_sys"

[build-dependencies]
pkg-config = "0.3"
